[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
lending_pool = "HLtWrvLyc2SE3ERWHaEdY4RG84GxFfHv3Qf4NzJPxaF7"
nullifier_registry = "E42nSmqvSCuC1EWbmzYqsdLHimBMeuZyir5dB5gE24rF"
shielded_pool = "9Bvt3jMawHFRRxpaQTtV5VvFdpZkmAZtvwjTrAX9TAtE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test:anchor"
