/* global React, Icon, PrivacyDisclosurePanel, NoteStatusBadge, RingMeter, StepperRow, SL_DATA, SL_FMT */
const { useState: useWState, useEffect: useWEffect } = React;

const WithdrawScreen = ({ mode }) => {
  const eligible = SL_DATA.notes.filter(n => n.status === "Active");
  const [selectedId, setSelected] = useWState(eligible[0]?.id);
  const sel = SL_DATA.notes.find(n => n.id === selectedId) || eligible[0];
  const [submitted, setSubmitted] = useWState(false);
  const [proofStep, setProofStep] = useWState(0);

  useWEffect(() => {
    if (!submitted) return;
    let cancel = false;
    (async () => {
      for (let i = 1; i <= 4; i++) {
        await new Promise(r => setTimeout(r, 1300));
        if (cancel) return;
        setProofStep(i);
      }
    })();
    return () => { cancel = true; };
  }, [submitted]);

  const ringOk = sel.ringReady >= 16;

  return (
    <div className="col gap-32 fade-up">
      <ScreenHeader
        eyebrow="Operation · 02"
        title="Withdraw."
        sub="Spend a note to a fresh stealth address. The ring proof hides which note. Umbra hides the destination."
      />
      <div style={{ display: "grid", gridTemplateColumns: "minmax(0, 1.6fr) minmax(0, 1fr)", gap: 24 }}>
        <div className="col gap-20">
          <div className="card-hairline" style={{ padding: 0 }}>
            <div className="row" style={{ justifyContent: "space-between", padding: "16px 20px", borderBottom: "1px solid color-mix(in srgb, var(--fg-quaternary) 40%, transparent)" }}>
              <span className="t-micro fg-tertiary">Eligible notes</span>
              <span className="t-caption fg-tertiary">{eligible.length} active · ring K=16</span>
            </div>
            {eligible.map(n => (
              <button key={n.id}
                onClick={() => setSelected(n.id)}
                className="row"
                style={{
                  padding: "14px 20px",
                  borderBottom: "1px solid color-mix(in srgb, var(--fg-quaternary) 30%, transparent)",
                  gap: 16, width: "100%", background: selectedId === n.id ? "color-mix(in srgb, var(--privacy-active-soft) 40%, var(--surface-1))" : "transparent",
                  border: "none", borderLeft: selectedId === n.id ? "2px solid var(--privacy-active)" : "2px solid transparent",
                  cursor: "pointer", textAlign: "left",
                }}
              >
                <NoteStatusBadge status={n.status}/>
                <div className="col" style={{ minWidth: 110 }}>
                  <span className="t-num fg-primary">{n.denom} SOL</span>
                  <span className="t-num-s fg-tertiary">{n.commitmentShort}</span>
                </div>
                <div className="col" style={{ minWidth: 90 }}>
                  <span className="t-caption fg-tertiary">DEPOSITED</span>
                  <span className="t-body fg-secondary">{SL_FMT.ago(n.createdAt)}</span>
                </div>
                <div style={{ flex: 1 }}/>
                <div className="col" style={{ alignItems: "flex-end" }}>
                  <span className="t-caption fg-tertiary">RING {n.ringReady}/16</span>
                  <RingMeter ready={n.ringReady}/>
                </div>
              </button>
            ))}
          </div>

          {sel && (
            <div className="card-hairline" style={{ padding: 18 }}>
              <div className="row" style={{ justifyContent: "space-between", marginBottom: 14 }}>
                <span className="t-micro fg-tertiary">Stealth recipient · single-use</span>
                <button className="btn btn-sm btn-ghost"><Icon name="refresh" size={12}/> Regenerate</button>
              </div>
              <div className="row gap-16">
                <div style={{ width: 88, height: 88, background: "var(--surface-emphasis)", borderRadius: 6, display: "flex", alignItems: "center", justifyContent: "center", color: "hsl(195 30% 8%)" }}>
                  <Icon name="qr" size={56}/>
                </div>
                <div className="col gap-6" style={{ flex: 1 }}>
                  <span className="t-num fg-primary">Stealth-3 · sl3x…f9p2</span>
                  <span className="t-caption fg-secondary">Generated by Umbra SDK from your meta-address. Has zero prior chain history. Forwarding to a known wallet creates a permanent public link.</span>
                  <div className="row gap-8" style={{ marginTop: 4 }}>
                    <button className="btn btn-sm btn-ghost"><Icon name="copy" size={12}/> Copy</button>
                    <button className="btn btn-sm btn-ghost"><Icon name="external" size={12}/> View on Umbra</button>
                  </div>
                </div>
              </div>
            </div>
          )}

          <div className="card-hairline" style={{ padding: 18 }}>
            <div className="t-micro fg-tertiary" style={{ marginBottom: 14 }}>Proof generation</div>
            <StepperRow active={submitted ? proofStep : 0} steps={[
              "Build ring of 16 commitments",
              "Generate Groth16 proof (snarkjs ~6s)",
              "IKA relay submits via PER exit batch",
              "Nullifier marked Spent on-chain",
            ]}/>
          </div>
        </div>

        <div className="col gap-16">
          <PrivacyDisclosurePanel
            mode={mode}
            hidden={[
              "Which deposit was spent (within 16-ring)",
              "Submitter wallet (relay routes)",
              "Recipient identity (Umbra stealth)",
            ]}
            observable={[
              "Nullifier marked Spent",
              `Denomination = ${sel?.denom} SOL`,
              "Stealth address receives funds",
            ]}
            responsibility={[
              "Sweep stealth carefully",
              "Avoid forwarding to KYC'd wallet",
              "Wait for full ring if degraded",
            ]}
            context={ringOk ? "Full anonymity set" : `Ring under-populated (${sel.ringReady}/16)`}
          />

          <div className="card-hairline" style={{ padding: 14, background: "color-mix(in srgb, var(--privacy-degraded-soft) 22%, var(--surface-1))" }}>
            <div className="row gap-10" style={{ marginBottom: 6 }}>
              <Icon name="warning" size={14} color="var(--privacy-degraded)"/>
              <span className="t-micro" style={{ color: "var(--privacy-degraded)" }}>Sweep anti-pattern</span>
            </div>
            <div className="t-body fg-secondary">
              Forwarding withdrawn SOL to a KYC'd exchange or a wallet that has interacted with KYC'd addresses undoes the privacy of this withdrawal. Hold, redeposit, or spend from the stealth address directly.
            </div>
          </div>

          <button
            className="btn btn-block btn-lg btn-primary"
            disabled={!sel || submitted}
            onClick={() => setSubmitted(true)}
          >
            {submitted ? `Generating proof… ${proofStep}/4` : `Withdraw ${sel?.denom} SOL`}
          </button>
          <div className="t-caption fg-tertiary" style={{ textAlign: "center" }}>Fee · 0.00012 SOL · proof gen ~6s</div>
        </div>
      </div>
    </div>
  );
};
window.WithdrawScreen = WithdrawScreen;
